# site settings
title: CO-OP
subtitle: TRAIL
email: info@cooptrail.org
description:
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone: (773) 263-0181

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
instagram_url: https://www.instagram.com/coop_trail/
linkedin_url:
slack_url:
twitter_url: https://twitter.com/TheCoopTrail

# build settings
markdown: kramdown

sass:
  style: compressed
