# site settings
title: CO-OP TRAIL
subtitle:
email: thecooptrail@gmail.com
description: 'Regenerative travel in the regenerative economy'
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
hylo: https://www.hylo.com/groups/coop-trail

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/CoopTrail
instagram_url: https://www.instagram.com/cooptrail/
linkedin_url:
slack_url:
twitter_url: https://twitter.com/TheCoopTrail
youtube_url: https://www.youtube.com/channel/UCjcZqjYIyFCo9SC0YaBy6Mg
tiktok_url: https://www.tiktok.com/@thecooptrail

# build settings
markdown: kramdown

sass:
  style: compressed
